import express from"express";
import { authmiddleware } from "../middleware/AuthMiddleware.js";
import {getAllNotes, getNote, createNote, updateNote, deleteNote} from '../controllers/notesController.js';
const router = express.Router();
router.get('/', authmiddleware, getAllNotes);
router.get('/:id', getNote);
router.post('/', authmiddleware, createNote);
router.put('/:id', updateNote);
router.delete('/:id', deleteNote);
export default router;